name: Continuous Integration

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
        cypress-version: [10.11.0, 11.2.0, 12.2.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: bash test.sh ${{ matrix.cypress-version }}
